apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: llm-workload
  labels:
    cni: calico
    cluster-api.cattle.io/rancher-auto-import: "true"
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
        - 10.96.0.0/24
  topology:
    class: docker-llm-clusterclass
    controlPlane:
      replicas: 1
    version: v1.28.0
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          metadata:
            annotations:
              cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "1"
              cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "3"
              capacity.cluster-autoscaler.kubernetes.io/cpu: "2"
              capacity.cluster-autoscaler.kubernetes.io/memory: "4Gi"
